# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('buildingName', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('companyId', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=5, max_digits=10)),
                ('photo', models.CharField(max_length=50)),
                ('streetName', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
